### ISSUE TITLE
Documentation link on main github page seems to be wrong

### ISSUE THREAD

**Issue by h-mayorquin** [JaneliaSciComp/PyWaveSurfer#162]
So the link in the documentation (bottom right): 

![image](https://user-images.githubusercontent.com/6429509/196486503-fbce7b8f-f85a-42c4-a94a-aa901bbb8087.png)

Leads here:
https://wavesurfer.janelia.org/manual/index.html
Which looks like this:
![image](https://user-images.githubusercontent.com/6429509/196486753-cb800028-4d84-48f2-aab2-f6d5d295bedf.png)

This does not seem right. I guess instead it should lead here somehow?
https://wavesurfer.janelia.org/manual-0.945/index.html

**Comment by boazmohar** [comment]
Hi @h-mayorquin, 
Good catch, I have updated the link.

Thanks,
Boaz
