### ISSUE TITLE
Problem on executing example codes

### ISSUE THREAD

**Issue by skw517** [JaneliaSciComp/PyWaveSurfer#177]
pip install pywavesurfer

import pywavesurfer

from pywavesurfer import ws

TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'

Hi there. I am trying to analyze audio data and convert it to wave.
The codes above are the codes I have executed on virtual environment
but i got stuck in the typeerror that i noted above when running 'from pywavesurfer import ws' 

I wonder how can I handle this. Thank you

**Comment by boazmohar** [comment]
Hi @skw517, 

Would you mind providing the entire error message?
Also what OS / virtual environment manager are you using so I could try to reproduce...

Just to make sure, pywavesurfer is for acquisition of analog signals from electrophysiological experiments (usually) :)

**Comment by skw517** [comment]
What a fast response

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_8968\3444183845.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/User/kdt/mysite/kdt/~/AppData/Local/Temp/ipykernel_8968/3444183845.py) in 
----> 1 from pywavesurfer import ws

[c:\anaconda\envs\new_env\lib\site-packages\pywavesurfer\ws.py](file:///C:/anaconda/envs/new_env/lib/site-packages/pywavesurfer/ws.py) in 
      9 # the latest version pywavesurfer was tested against
     10 _latest_version = 0.97
---> 11 _over_version_1 = SpecifierSet(">=1.0")
     12 
     13 # from pywavesurfer.ws import * will only import loadDataFile

[c:\anaconda\envs\new_env\lib\site-packages\packaging\specifiers.py](file:///C:/anaconda/envs/new_env/lib/site-packages/packaging/specifiers.py) in __init__(self, specifiers, prereleases)
    712         elif not isinstance(other, SpecifierSet):
    713             return NotImplemented
--> 714 
    715         return self._specs != other._specs
    716 

[c:\anaconda\envs\new_env\lib\site-packages\packaging\specifiers.py](file:///C:/anaconda/envs/new_env/lib/site-packages/packaging/specifiers.py) in __hash__(self)
    337                 # operators separately to enable that.
    338                 (?<===|!=)            # Only match for equals and not equals
--> 339 
    340                 \s*
    341                 v?
...
--> 334             (?:
    335                 # The (non)equality operators allow for wild card and local
    336                 # versions to be specified so we have to define these two

TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?8fa3aebf-a6bf-4d50-9a63-15ae9bba2bce) or open in a [text editor](command:workbench.action.openLargeOutput?8fa3aebf-a6bf-4d50-9a63-15ae9bba2bce). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

This is the whole error message 

Well I was trying to convert the audio data to wave.. I asked to Bard about pywavesurfer and he replied that it is possible to visualize the wave of audio via pywavesurfer. Is it possible? Or does pywavesurfer fit with my purpose? Thank you

**Comment by skw517** [comment]
And I created virtual environment by using conda

**Comment by boazmohar** [comment]
Ah the rise of AI ;)
I think you are looking for this JS project:
https://wavesurfer-js.org/
Our project will not be able to visualize wave files...

You might be able to run it from python with something like this:
https://cm-gitlab.stanford.edu/kittyshi/espressionizer/blob/master/expRun.py

**Comment by skw517** [comment]
Thanks a lot!

Well I am trying to run it from python so I should try the latter one you gave 

The latter one looks like the one I can visualize mp3 or wav files  Am I right?

And Bard gave some recommendation on the models that I can convert kind of audio files into wave, and there was librosa also.

If you know about librosa well, I'd like to get some advice on using librosa to convert audio files into wave

**Comment by boazmohar** [comment]
Sorry, but that is my extent of python and visualization of wave files. 
A quick goolge search shows you can load wav files with scipy:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.read.html
Then you can plot them in matplotlib:
https://matplotlib.org/stable/tutorials/index.html
